### ISSUE TITLE
verify results

### ISSUE THREAD

**Issue by ndmanifold** [ryanzhumich/editsql#11]
Hi,

Thanks for the code. 

I ran the test_sparc_editsql.sh script, now I see 
`valid gold-passing STRING_ACCURACY:     53.78`
in log.txt
Is this same as  EditSQL (use gold query) | 53.4 ?
Also, can you please tell me where is _interaction match accuracy_ is calculated?

Thanks a lot

**Comment by ryanzhumich** [comment]
Thanks. The final evaluation results are calculated by `python3 postprocess_eval.py `command, and the results are saved as [valid_use_predicted_queries_predictions.json.eval](https://github.com/ryanzhumich/editsql/blob/master/logs/logs_sparc_editsql/valid_use_predicted_queries_predictions.json.eval).
This corresponds to EditSQL (use predicted query) 47.2 | 29.5.

Note that the gold-passing STRING_ACCURACY is not the final evaluation results. Sorry about this confusion.

**Comment by ndmanifold** [comment]
Thanks for the reply. :)

Just to confirm: 
(0.622 * 421 + 0.451 * 421 + 0.361 * 269 + 0.193 * 88) / (421 + 421 + 269  + 88 + 1) = 0.471521
is the way to calculate?

What about the interaction match? Is that getting printed anywhere?

Thanks
