### ISSUE TITLE
Some problem with logs/logs_spider_editsql/save_12

### ISSUE THREAD

**Issue by HualeiZhuu** [ryanzhumich/editsql#12]
When I ran the command "git lfs clone https://github.com/ryanzhumich/editsql", there was an error:
![image](https://user-images.githubusercontent.com/18155049/72337295-4d50fb00-36fd-11ea-8dd4-cc6a3263f759.png)
And the trained model logs/logs_spider_editsql/save_12 is a txt file:
![image](https://user-images.githubusercontent.com/18155049/72337437-88532e80-36fd-11ea-9078-370eedaf497d.png)
What is the reason? 
Anyone help me? Thanks a lot!

**Comment by ryanzhumich** [comment]
Sorry about this. I just shared save_12 using a google drive link. Can you please try again? Thanks!

**Comment by HualeiZhuu** [comment]
Great. Thanks a lot!

By the way, is the accuracy 58.0 using the save_12? The evaluation result locally is different from the result in the paper.

**Comment by ryanzhumich** [comment]
Thanks. Did you use postprocess_eval.py to produce the evaluation results?

**Comment by ryanzhumich** [comment]
Thanks for letting me know! I think 57.6 vs 58.0 should be okay.
