### ISSUE TITLE
If we have enough data, what will the model achieve for hard SQL?

### ISSUE THREAD

**Issue by guotong1988** [ryanzhumich/editsql#4]
We are afraid that the hard SQL like TABLE JOIN is the limit for industrial application.

Thank you very much.

**Comment by slamandar** [comment]
I personally think the limitation is not only in the amount of data, but also how to correctly combine the database with the natural language, and how to generate SQL in real sense, instead of generate SQL word by word use LSTM, which is not in accordance with the way humans write code.
