### ISSUE TITLE
how to run editsql on cosql?

### ISSUE THREAD

**Issue by runzewang** [ryanzhumich/editsql#7]
I run the run_cosql_cdseq2seq.sh follow the readme, but I can't get the log file like logs/logs_cosql_editsql/log.txt. What should I change?

**Comment by ryanzhumich** [comment]
Thanks. I just uploaded run_cosql_editsql.sh and test_cosql_editsql.sh. For test_cosql_editsql.sh, you need to first download the trained model as described in README.
