### ISSUE TITLE
I was wondering how to repeat your experiment

### ISSUE THREAD

**Issue by ygan** [ryanzhumich/editsql#8]
Hi,
I was wondering whether you could provide guidance to repeat your experiment.
I can not generate the final output to evaluate the results. 
It seems the ``eval_step'' function in the model is deleted.
So how can we generate the final SQL output through inputting the dev.json? 
I can only get 23.60% in valid gold-passing STRING_ACCURACY without BERT.
Maybe I make some mistakes or it may improve when evaluating it in Spider exact match evaluation method. 
So I was wondering what I should do to get the same results as your paper.
Thank you.

**Comment by ryanzhumich** [comment]
Hi,

We have uploaded our trained model with Spider at logs/logs_spider_editsql/save_12, and the script to test it on dev split at test_spider_editsql.sh.

This can generate the final SQL output and evaluation results on Spider.

**Comment by ygan** [comment]
Thank you for your help.
However the script test_spider_editsql.sh run with bert. I was wondering whether the save_12 can run without bert?
