### ISSUE TITLE
Batch training for spider dataset

### ISSUE THREAD

**Issue by DreamerDeo** [ryanzhumich/editsql#9]
Hi,

I notice that in the training bash for spider, the interaction_level was set for true. 
Should I run spider (actually no interaction) in this setting ? 
Since the current setting is:
a) batch-size was set to 1 in `run.py` (L48) 
b) interaction_level

Is batch training available in interaction level using `schema_interaction_model`?

Thanks in advance!

**Comment by DreamerDeo** [comment]
1.Remove the assert in train_epoch_with_interactions 
2.Set the batch-size in run.py (L48) with args.batch_size

**Comment by ryanzhumich** [comment]
Please note that we do require the assert in train_epoch_with_interactions

args.batch_size can still be larger than 1 and is used to normalize the loss
